### ISSUE TITLE
help with help. explain how help works

### ISSUE THREAD

**Issue by dominictarr** [ssbc/muxrpcli#5]
there are lots of help.js in each plugin now, but @corlock asked me how that worked, and where that should be documented. muxrpcli is the entry point for that, so this should probably describe how to add a help method.

see also https://github.com/dominictarr/muxrpc-usage

**Comment by corlock** [comment]
@dominictarr , see here: https://github.com/dominictarr/epidemic-broadcast-trees/issues/24#issuecomment-475829798

You need @clevinson
